### ISSUE TITLE
[bug] RainbowKitProvider adds styles and a block element in my page that makes lines break

### ISSUE THREAD

**Issue by TimDaub** [rainbow-me/rainbowkit#1404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.12.15

### wagmi Version

0.12.13

### Current Behavior

<img width="1236" alt="Screenshot 2023-07-14 at 17 24 02" src="https://github.com/rainbow-me/rainbowkit/assets/2758453/d2afb8e2-a0d7-401f-a858-48c17602de7f">

I recently switched from ConnectKit to RainbowKit and now the RainbowKitProvider adds this div element that makes my button have a line break. Here's that code: https://github.com/attestate/kiwistand/blob/main/src/web/src/NFTPrice.jsx#L117

### Expected Behavior

It should not add a div with styles. But if it did, it should not interfere with my styling of the page

### Steps To Reproduce

You can go here and see for yourself: https://news.kiwistand.com/welcome

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://news.kiwistand.com/welcome

**Comment by DanielSinclair** [comment]
@TimDaub 
- It looks like you're using `RainbowKitProvider` and `WagmiConfig` in multiple places. You typically would want to share this at the layout/nav level, as the Wagmi client is a singleton, and you can use Wagmi hooks anywhere down the component tree. Checkout our examples [here](https://github.com/rainbow-me/rainbowkit/tree/main/examples) to see what that should look like. RainbowKit will inject this div at the root level, but there shouldn't be any styling naming clashes.
- It looks like the linebreak problem was resolved on your end, so will close this out. Lmk if you're still running into issues.
<img width="854" alt="Screenshot 2023-07-14 at 7 28 24 PM" src="https://github.com/rainbow-me/rainbowkit/assets/4412473/cc0a9cc7-a89a-4431-ad90-b8d14155e665">

**Comment by TimDaub** [comment]
I‘m using react in an Island style approach. So necessarily that‘ll mean that RainbowKitProvider is inserted many times. I solved the problem by removing the RainbowKitProvider from that component entirely. But the problem persist for other users. You wanna use a span to bundle elements in the Provider, not a div as to not force line breaks in dev‘s layouts.
