### ISSUE TITLE
Rainbowkit unable to connect to metamask sometimes

### ISSUE THREAD

**Issue by jtfirek** [rainbow-me/rainbowkit#1759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.5

### wagmi Version

1.4.13

### Current Behavior

When the user presses the metamask button and they have metamask installed, rainbow kit thinks they don't have metamask and doesn't connect

### Expected Behavior

When the user presses the metamask button and they have metamask installed, they should have a pop up from metamask to connect to the site

### Steps To Reproduce

- go to:
https://www.rainbowkit.com/docs/introduction

- press the connect button with metamask installed:

### Anything else?

<img width="1673" alt="Screenshot 2024-02-07 at 10 25 15 PM" src="https://github.com/rainbow-me/rainbowkit/assets/106350168/58461046-5e3d-4621-8423-a0c0764798f1">

**Comment by KosmosKey** [comment]
@jtfirek Thanks for reporting this issue 👍

If you try to disable other wallet extensions and only keep metamask would that work ? If that would work it's a problem with the [EIP1193](https://eips.ethereum.org/EIPS/eip-1193). Meaning the other wallets can block the access for metamask to work and override `window.ethereum`. I see you also have coinbase wallet and many people have issues with that as well.

But we're releasing RainbowKit v2 soon and we will introduce EIP6963 which should fix this issue. 

Let me know if this is helpful 🙏

**Comment by KosmosKey** [comment]
@jtfirek We just released RainbowKit v2. Do you mind upgrading to the latest version and let me know if the issue still persists ?

**Comment by Frontend-io** [comment]
Thanks @KosmosKey, facing this same issue, I have just upgraded to v2 but the issue persists.

If you try to click on Metamask on your documentation, it doesn't work as well: https://www.rainbowkit.com/docs/wallet-button

**Comment by KosmosKey** [comment]
@Frontend-io Does it not work with RainbowKit modal or does it not work with WalletButton ? 

In your case you're using a wallet that overrides `window.ethereum`'s metamask which blocks metamask being detected in the network. We're still using EIP-1193 for `<WalletButton />` specifically, but should work just fine like this:

![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/c61cc922-36de-4621-b2fe-be2026f524ea)

**Comment by Frontend-io** [comment]
Thanks, @KosmosKey, I think that is the case (that another wallet overrides it). I tried with another browser with only metamask installed and it worked fine. `window.ethereum` returns the ethereum object with `{..., isMetamas: true}` 

My other wallets are useful as well, is there a way around this just uninstalling the other wallets?

**Comment by KosmosKey** [comment]
> Thanks, @KosmosKey, I think that is the case (that another wallet overrides it). I tried with another browser with only metamask installed and it worked fine. `window.ethereum` returns the ethereum object with `{..., isMetamask: true}`
> 
> My other wallets are useful as well, is there a way around this just uninstalling the other wallets?

With RainbowKit connect modal it should work just fine. Just make sure you enable the metamask + with other wallets and click "MetaMask" on the "Installed" section. There should be no conflict due to the new EIP-6963 feature we've added.

![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/deac331f-339a-46e3-9a0a-a03725a9e47c)

Regarding the `<WalletButton />` we'll add support for that soon, but even wallets like Coinbase wallet are causing issues with `window.ethereum` overrides. Usually it's the wallets faults for causing those conflicts, but should be fixed specifically for `<WalletButton />` soon.

**Comment by Frontend-io** [comment]
Thanks for the quick responses @KosmosKey . Yes, before i fix is released for the WalletButton, i've temporarily removed coinbase wallet, my metamask works fine now. Coinbase wallet was the one overriding it. Much love ❤️

**Comment by KosmosKey** [comment]
@Frontend-io Sounds good. We will make sure to add support for WalletButton with EIP-6963, but happy that it works with connect modal for now.

**Comment by duong-doan-dev** [comment]
I also face this problem with WalletButton. Tried to connect to Metamask but the address is of Zerion wallet. Maybe I should use Modal for now. Hopefully EIP-6963 will be applied to WalletButton soon

**Comment by KosmosKey** [comment]
> I also face this problem with WalletButton. Tried to connect to Metamask but the address is of Zerion wallet. Maybe I should use Modal for now. Hopefully EIP-6963 will be applied to WalletButton soon

Yes use Modal for now and we'll add support for EIP-6963

**Comment by wahabshah21** [comment]
Hi I have just this issue that my metamask would connect properly but then sometimes after I disconnect it and try to connect it I get the modal message like "Opening MetaMask. confirm connection in extension..." but the metamask doesnt open. Then if I refresh the page it starts working again.

Is it some cache issue with rainbowkit or maybe provider and I need to reset it somehow on disconnection?

![image](https://github.com/user-attachments/assets/cef011c0-277c-4b06-b09d-a40c375a2919)

**Comment by magiziz** [comment]
@wahabshah21 Did you upgrade your `wagmi` version to `2.12.0` ?

**Comment by wahabshah21** [comment]
No I am using 2.9.10. Will upgrading it solve the issue?

**Comment by DanielSinclair** [comment]
@wahabshah21 I believe so. Wagmi improved how they handle connectors in this recent release. Let us know if your issue resolves after upgrading; there shouldn't be any breaking changes beyond that.

**Comment by wahabshah21** [comment]
Hi. I am facing one strange issue. 

All of a sudden happened, when I click on wallet connect the rainbowkit modal opens and then once metamask is selected, metamask opens. After I click the connect button in metamask, it shows connecting and the closes but wallet isnt connected and I see the retry button in rainbowkit Modal.

Even after clicking on retry same thing happens as explained above. However if I go manually in metamask extension, choose different account to connect then it starts working and then I can switch between accounts too. 

Same issue after disconnecting the wallet again.

I am curios because it started happening this morning and it was working previously perfectly. What could be the possible issue?
I have updated the version of both wagmi and rainbowkit wallet (to latest ones). But Still facing this wallet connection issue.

Any help or direction is appreciated.

Keeps on showing this even after confirmed from metamask (screenshot attached below)

![image](https://github.com/user-attachments/assets/74ed1eee-39f4-4476-8a97-d4944acb0cf0)

**Comment by Denverr0987** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by PATEL96** [comment]
I am Also facing the same Issue when trying to use the latest `wagmi` version.

I guess this maybe some kind of connector issue on wagmi's end?

**Comment by moneyDev1111** [comment]
me too........... no matter what I use a custom btn or a factory one, with or without project id etc etc, metamask won't connect, just "Opening MetaMask...
Confirm connection in the extension" and nothing happens........ wagmi works, it invokes any wallet. but the rainbow kit button doesn't do anything
