### ISSUE TITLE
[bug] ethers dependency

### ISSUE THREAD

**Issue by soccerarenadev** [rainbow-me/rainbowkit#762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.6.0

### wagmi Version

0.6.6

### Current Behavior

When trying to install dependencies having a newer version of ethers, I get this error, unless I use --force.
I'm currently using ethers 5.7.1. But seems to be incompatible with rainbowkit-siwe-next-auth.

```
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer ethers@"5.5.1" from siwe@1.1.6
npm ERR! node_modules/siwe
npm ERR! siwe@"^1.1.6" from the root project
npm ERR! peer siwe@"^1.1.6" from @rainbow-me/rainbowkit-siwe-next-auth@0.1.3
npm ERR! node_modules/@rainbow-me/rainbowkit-siwe-next-auth
```

**Comment by adbario** [comment]
@soccerarenadev This is related to the `siwe` version. In [v2.0.3-beta](https://github.com/spruceid/siwe/releases/tag/v2.0.3-beta) they updated the `ethers` version; before that, you'll get the error described above. The current latest `siwe` version is `2.0.5-beta` and upgrading to that should solve the issue.

**Comment by soccerarenadev** [comment]
> @soccerarenadev This is related to the `siwe` version. In [v2.0.3-beta](https://github.com/spruceid/siwe/releases/tag/v2.0.3-beta) they updated the `ethers` version; before that, you'll get the error described above. The current latest `siwe` version is `2.0.5-beta` and upgrading to that should solve the issue.

I've tried updating the siwe version. And still the same error. I guess we should wait rainbowkit-siwe-next-auth to update it as well.

**Comment by anteqkois** [comment]
Please update `siwe` package, every time I want to use it it is impossible and I have to think for a few hours how to solve it so that the program does not crash

**Comment by adbario** [comment]
> Please update `siwe` package, every time I want to use it it is impossible and I have to think for a few hours how to solve it so that the program does not crash

Until `siwe` is updated, you can just copy over the `rainbowkit-siwe-next-auth` [source files](https://github.com/rainbow-me/rainbowkit/tree/main/packages/rainbowkit-siwe-next-auth/src) into your ts project and use any `siwe` version you like.

**Comment by DanielSinclair** [comment]
Hi all! We're working on getting the updates to `siwe` into RainbowKit to resolve this peer dependency conflict. We're working with Spruce on this, and expect their prod API to settle soon. https://github.com/spruceid/siwe/pull/138
